language: node_js
node_js:
- 6
addons:
  firefox: 49.0.1
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
script: npm run dist
notifications:
  slack:
    secure: DKGiMzWLoYGhIxS9mbSbBNpNRv3rCKAhKuXRqQ9gYLnX11A0i13/2uJlq9fDd2N4hmyvsMaLQEpy+QbEk53jIz+95jC6qUeJNCYRjPv7V+JfoU2HKa+9BRcMZtxh4qitJaxnsaHW62h7m5NCrsLi9fa7QTpjPOOMjts9tb6EzPgkpCTSRgM8kLgDUxfqkHcZO+yPowhvz/QhYJiNVl+XD9BhRAZBc6NFuBlgJfFhgoC514crggscLkdoQFTyonlbWI2O921MBe9/TTp56jEQl5wqnxJ52XO7/jiGF3GtWGZ7jXvEQ0g1DN28tYzP3okmcueKA/gLUb+cuPkooiS9jFzA98aZ+NlNOtGimE811RDWHCCmJlFuLqRXSVTj6MpN4WZ7DnoHgR9BqP3h7CYLwBiKXrzvgfNm/qn9HjL9JXiZFFnAqteFrLB+rfD0q4/YdalMLzdVqY5tcT53MWzr/fPxj4rJlYm1uVIHsoyhVGrcFU4muzHOBUG1TIlYMfhw3K16TaCQ5MvJ1VPq/p/Yid+91Jh3PR94DLfgpKOmiuG/elHjTig8/F1Or9OU6yQh58L/a8tdjhF9zNpvQbpxdJilXvTvYqhiHQP0QNZ24lpkJ5B3GG8sVkwVTC4A2lVbjQrHT22f9v9X9gW6pwFMTAzpQftex8kGMDslT4t4Foo=
    on_success: change
    on_failure: always
deploy:
  - provider: releases
    api_key:
      secure: TST6UXAa8MhxSk11M3+YYLD1mXwAptFZulfh4pzQuBt60F0ruyBfspni0VJfVkTDK1W7GNey8FzePUC6zzBmWICFnHvPk6hVXDbhqeoi7Lzg1Eq7YTk0Jx+hwAao6bbFXI2/xSh9QfqsuyKL7rsbkA3gXB/ITwzg4Z76Dq1W82afTBPlgTIDafYP6VLd8JGEpTzAe7afJvH9Gd3HoIvMQEU53hd6DpM1v6vYkumZ+tevwfZ91HiRQ5K2GWa9z3uV0SHvqTS6Kk/QnZ+F1YbEmgZ8FNZ4dhTV8kBzbWyNK+5tFKYXkbqLTTeH5HHQWZrXSnN+yBh16rGz1V2Skbn60AYTJMUKGrKscWzx1jzmiHJlIJtRL6NCCY6F6JvcVJ5+z14HnE+E5/nS39UPMihtaiRdKWlhpyd2tjUPzumyWY8H0NiPvO5hKHeA9ISyQJ52gczORNr7e7F+WPHu1ywtCwjSM4JdmGxE483zTq4jW2jUTe0WaTy/rQfC4oMR/ZhdZO+vMllxEW3AsTjSAMyKJY2yilUFLS5o/I/k6TxWNSiujFaD4d3K7WKIlrk0xZer7ndr3n1tTBSzIOI60xPcnfx4HeV0e4z1nTQsU2meznM/Xc2s1CLS2avXLKUV9mHYkRxBT4fnfFIS7zNpn7IJtKyCaI/XKAH4t/9yiVlVikM=
    file: dist/phovea_d3.tar.gz
    on:
      tags: true
      repo: phovea/phovea_d3
  - provider: npm
    email: samuel.gratzl@jku.at
    api_key:
      secure: Af5t/57xLVGgUUjkRfYPBkVWl6qjACnhOQqjIABFKLpZi1zpmPHC8BS2/STFnmgZ8XA+FWD2qrycqiLJokPsL2NbD9wXLH0qNTtD+u4psnyw3kNmKtfC3pz+7Sp7mSWeTGe9XAj0XzfGnEjFy84LckWSy/EfaqASTTDnOozkh4NmKKAprpO33KTLfQX0zZJKzxXp34OQgZDGpDp/li2I/OP/K3xDz49BE3r/IaMW5JmKRL+yZ5hlpDW0WgBtZy/DgYNJJQ5InrZWFmuyAIstaXS10hczrShhIHYkFhqYIlZVHdZVVo2mhmqGa2HhNaPyO2lSMqRQhAhZDydAbi1kcVJyyPEFkM040XnxiohJeaYkkKhPlUHQ/uPA8KaMqVSsXoLgW80WU1piulXHC71ETKauw9XRzxwh+X5SbTp9ezJzDm7DyptfW6XQTUHBrs2IgrqphbsY0PeUcpCsyDwP4kOy4WiUUgatxxABCrXhSK+HVEdcFH/wcBbI7yTqahys/8zviFr+ytnUmaFqu0IsZNscQBMuQO4lyZdTmA7Xm/wJL0LSkzbTEWcHSG/O/2TWLTGtLElvpi9BA7myTzvA+mB++GwVfzXvXjH8i/iPVAzuSQKKWs3TvrLqWPWma+TnaB9rciQ6MpN0V0MOUUaD/572rN/aGt6aH2OYNeSjdV0=
    on:
      tags: true
      repo: phovea/phovea_d3
